### ISSUE TITLE
Dailies posted at reset are wrong

### ISSUE THREAD

**Issue by HumorLlama** [Maselkov/GW2Bot#115]
Added the bot to a Discord server and set it up to post the Daily PvE / Fractals / Strikes on reset. When the bot makes the post, these are all incorrect.

For 4/24/2022's reset post the PvE Dailies the bot lists are:
Citadel of Flame
Desert Forager
Desert Vista Viewer
Kryta Vista Viewer
Maguuma Wastes Forager

In game the PvE dailies are:
Daily Maguuma Wastes Miner
Daily Activity Participation
Daily Lornar's Pass Event Completer
Daily Bad Neighborhood Minidungeon
Daily Completionist

Running the /daily command to manually have the bot post the pve daily again to double check (and ensuring the tomorrow value was not included) gets the same results.

**Comment by Maselkov** [comment]
The daily API endpoint is having issues at the time. Nothing to do with the bot, alas.
