### ISSUE TITLE
Improvement suggestions / Typo fixes / Semantics

### ISSUE THREAD

**Issue by brybrant** [Maselkov/GW2Bot#116]
`/achievement achievement`
argument name and description is identical to command name and description:
> "Display achievement information and your completion status"

more semantic name and description would be something like:
> name: "achievement_name"
> desc: "Name of achievement. Example: Playing Chicken"

---

`/evtc api_key operation`
typo in argument description:
> "operaiton" > "operation"

---

`/evtc autopost add_destination`
typo in subcommand description:
> "too" > "to"

---

`/evtc autopost remove_destinations`
command description could be clearer:
> "Remove EVTC autoupload destinations from a list"

could be changed to:
> "Removes all Discord channels from the list of autopost destinations"

(assuming that's how it works? I don't personally use the evtc command)

---

`/gem price quantity`
argument description is identical to command description:
> "Lists current gold/gem exchange prices"

more semantic description would be something like:
> "The number of gems to evaluate (default is 400)"

---

`/guild log`
command description inconsistent with website:
> "Get log of stash/treasury/members"
> "Get log of last 20 entries of stash/treasury/members"

---

`/guild log log_type`
typo in argument description:
> "The type of log to inspectguild. Required otherwise." > "Select the type of log to inspect"

---

`/guildsync edit operation`
Add conditional plural to argument options:
> "Toggle syncing ranks. If disabled, this will delete the role**(s)** created by the bot."
> "Toggle guild role. If disabled, this will delete the role**(s)** created by the bot."

---

`/guildsync edit api_key`
Possibly redundant optional argument? The argument description references a non-existant "authentication_method" argument; perhaps accidental copypasta from `/guildsync add`?

---

`/key info`
quality of life suggestion: would be nice to have an optional "index" argument like the `/key switch` command, to get info about a key without needing to switch first.

---

`/key remove`
same as above.

---

`/key switch index`
Less ambiguous argument description:
> "Key index to switch to. Skip to get a list instead."

could be changed to:
> "Key index to switch to. Skip to select from a list instead."

---

`/nodes`
command description inconsistent with website:
> "Displays the nodes you haven't unlocked. Required permissions: progression"
> "Displays the home instance nodes you have not yet unlocked (Requires "progression" permission)"

---

`/notifier bosses edit`
argument name and options could be made consistent with `/notifier daily behavior` argument:
> rename argument from "edit" to "behavior"
> change description to "Select behavior for posting/editing the message. Defaults to posting a new message"
> change option "True" to "Edit the previous message. No unread notification"
> change option "False" to "Post a new message. Causes an unread notification"

---

`/notifier daily behavior`
one argument description could be made clearer:
> "Delete the previous day's message. Causes an unread notification"

could be changed to:
> "Delete the previous day's message and post a new message. Causes an unread notification"

---

`/notifier mystic_forger`
typo in subcommand description:
> "Forget" > "Forger"

---

`/notifier news`
quality of life suggestion: would be nice to have an optional "mention" argument like the `/notifier update` command, to ping a user/role/everyone

---

`/pvp professions profession`
argument description could be improved:
> "Profession for profession specific statistics"

could be changed to:
> "Select a profession to view specific statistics"

---

`/sab * character`
argument behavior could be made consistent with `/character` commands such as `/character gear` for example:
> character (optional argument): "Character name to inspect. Skip to get a list instead." - allows selecting from a drop-down list.

---

`/search item`
argument description could be made clearer:
> "Find items on your account"

could be changed to:
> "Specify the name of an item to search for"

---

`/server force_account_names enabled`
argument description is identical to command description:
> "Automatically change nicknames to in-game names"

could be made consistent with `/server preview_chat_links enable` argument description:
> "Enable or disable automatically changing user nicknames to match in-game account names"

---

`/tp price item`
argument description is identical to command description:
> "Check price of an item"

could be changed to:
> "Specify the name of an item to check the price of"

---

`/wiki language`
argument option "se" should be "es" for Spanish.
argument options could be changed to proper language names:
> "en" -> "English"
> "de" -> "German (Deutsch)"
> "fr" -> "French (Français)"
> "es" -> "Spanish (Español)"

---

`/worldsync enabled`
should this argument be required like it is now?

---

`/wvw info`
typo in argument description: double quote instead of apostrophe: "account's"

---

`/wvw poptrack world`
 argument description describes the argument as being optional, however this argument is actually required:
> "World name. **Leave blank to use your account's world**"

could be changed to:
> "Specify the name of a World to track the population of, and recieve a notification when the specified World is no longer full"

**Comment by Maselkov** [comment]
Done
