### ISSUE TITLE
add EoD Strike Missions, SM CMs to `/kp`

### ISSUE THREAD

**Issue by Fishrock123** [Maselkov/GW2Bot#117]
End of Dragons Strike Missions and their respective CMs should ideally be added to `/kp`, if that information is available in the API.

**Comment by Maselkov** [comment]
Absolutely! I'd appreciate if someone could collect the necessary IDs for it, otherwise, I'll do it when I've got time.

**Comment by Fishrock123** [comment]
I don't think that was the correct list of achievements.

It's missing `Legendary Aetherblade Hideout` (Mai Trin CM) and `The Path Of Most Resistance` (Overlook Title Achieve). The wiki doesn't seem to have those IDs and I don't know how to get them.

Also I don't think that the non-group achievements are relevant for kp, they just make it extra noisy or show-off-y.
List of achieves I think should be removed:
- `"Leaps Abound"`
- `"Total Coverage"`
- `"Clarity"`
- `"Out of Focus"`
- `"A Test of Your Reflexes"`

**Comment by Maselkov** [comment]
Thanks for the feedback! Your points are valid. I'll get onto it

**Comment by Fishrock123** [comment]
```
{{Achievement table row
| id = 6433
| name = Legendary Aetherblade Hideout
| page = Strike Mission: Aetherblade Hideout
| description = Complete the Aetherblade Hideout Strike Mission with challenge mode active.
| tiers = Completed the Aetherblade Hideout Strike Mission; 5
}}
```

Ok that's Aetherblade CM
