### ISSUE TITLE
/bosses command still shows permanent W7 call_of_the_mists

### ISSUE THREAD

**Issue by jqchang** [Maselkov/GW2Bot#122]
![image](https://user-images.githubusercontent.com/20122405/178114500-796f3f09-2c95-4d37-a9ca-71a847a035f8.png

Description:
After June 28 patch to Guild Wars 2, Call of the Mists system was changed in-game. "/bosses" command has not been updated to reflect these changes.

Steps to Reproduce:
1. Go to a channel (or DM) with GW2Bot
2. Enter "/bosses" command
3. See error

Expected behavior:
Bot output will show only one raid wing with Call of the Mists effect active, as well as one wing with Emboldened effect active.

Resulted behavior:
Bot output shows Call of the Mists effect active on two different raid wings. See screenshot.

**Comment by Maselkov** [comment]
Fixed! I think. Hopefully. Maybe. Possibly. Perhaps.
