### ISSUE TITLE
Rework update notifier to scrape the new forum

### ISSUE THREAD

**Issue by Maselkov** [Maselkov/GW2Bot#126]
The issue is twofold: /v2/build doesn't work anymore, and the forum had changed. The best way to check for updates now would be to regularly scrape the new forum, since it lacks a proper API, unlike the old one

**Comment by Invisi** [comment]
Until /v2/build works again, we could rely on the manifest (first number is the current build id) that's used by the game client as well.
http://assetcdn.101.arenanetworks.com/latest/101

**Comment by Maselkov** [comment]
Thanks for that link! I went ahead and used it for build checking for the new update notifier
