### ISSUE TITLE
GW2Bot Website has Expired Certificate

### ISSUE THREAD

**Issue by paguilera** [Maselkov/GW2Bot#161]
The certificate for the GW2Bot website has expired. Browsers are showing the site as unsafe as a result.

![gw2bot_expired_cert](https://github.com/user-attachments/assets/af787806-a4c8-4e6c-826c-9b74334dc20e)

**Comment by Maselkov** [comment]
Sorry, forgot to close, fixed thanks to the notice! Server related issue with automated renewals that I will resolve once I move the bot to a new environment
