### ISSUE TITLE
Assign role to all server members with a connected API key

### ISSUE THREAD

**Issue by autumnapsey** [Maselkov/GW2Bot#72]
I would like GW2Bot to assign a role to all server members who have set up their API key, preferably on server join or when the key is added thereafter.

**Comment by Maselkov** [comment]
What would be the main use case for this?

**Comment by Misuki-CG** [comment]
Mega-up of this issue. 

Multiple reason come to my mind : 
- Filter user that can use or not the bot, and guide them if necessary
- Authenticate user by guild wars account (can be helpful if you have to identify people in game & on discord at the same time) 
- More generally, can be use as a verification process (for guild members without using syncrole) 

I'm sure there are more reason to use this feature. Can also be related to [this issue](https://github.com/Maselkov/GW2Bot/issues/65#issue-355730395)

**Comment by Maselkov** [comment]
The reasons sound good and this feature would be pretty easy to add. I could use some name suggestions for the command, though :P

**Comment by Maselkov** [comment]
This is a thing now
