### ISSUE TITLE
BUG: character build and gear no longer display other user's public info

### ISSUE THREAD

**Issue by GostOmega** [Maselkov/GW2Bot#76]
I've been asked by my Raid Officers why the bot no longer will allow anyone to search each other's public character info for build and gear. We did some testing in the chat, and the two screenshots attached show the results.

Here we tested with my character setting being set to public (all):
![public_toggle](https://user-images.githubusercontent.com/18472043/59167273-60b03e00-8afe-11e9-899e-310417c5221b.PNG)

Here I switched it to private (all) to see what message we got:
![toggle_private](https://user-images.githubusercontent.com/18472043/59167276-6574f200-8afe-11e9-9fe9-6f7edbf79af5.PNG)

 The final picture shows that I have the proper permissions from the key to do the command as intended. ![key_active](https://user-images.githubusercontent.com/18472043/59167286-70c81d80-8afe-11e9-875b-77e1d763021c.PNG)

These commands are extremely helpful since our Discord server is to help teach raiders who are training to be better players, looking at their gear and build to provide accurate feedback is optimal for how we run our raids.

**Comment by Maselkov** [comment]
Fixed. Sorry it took so long, forgot about this issue!
